In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import os
print(os.listdir('/home/sourav/NeuralNetwork/Zoo Animal Classification'))
from sklearn.metrics import accuracy_score

['class.csv', '.ipynb', 'Prediction.ipynb', '.ipynb_checkpoints', 'zoo.csv']


In [3]:
df = pd.read_csv('/home/sourav/NeuralNetwork/Zoo Animal Classification/zoo.csv')

df.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [4]:
features = list(df.columns)
print(features)

['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type']


In [5]:
features.remove('class_type')
features.remove('animal_name')

print(features)

['hair', 'feathers', 'eggs', 'milk', 'airborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize']


In [6]:
X = df[features].values.astype(np.float32)
Y = df.class_type


print(X.shape)
print(Y.shape)

(101, 16)
(101,)


In [19]:
print (X
      )


[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(80, 16)
(80,)
(21, 16)
(21,)


In [28]:
import tensorflow as tf
from tensorflow import keras
model = tf.keras.Sequential()
model.add(keras.layers.Dense(units=5,  activation='relu', input_shape=[16,]))
model.add(keras.layers.Dense(units=8,kernel_initializer='he_normal',activation='softmax' ))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=400,verbose=1)
losst, acct = model.evaluate(X_test, Y_test, verbose=0)

Epoch 1/400
3/3 [==============================] - 0s 4ms/step - loss: 1.8979 - accuracy: 0.3750
Epoch 2/400
3/3 [==============================] - 0s 5ms/step - loss: 1.8776 - accuracy: 0.3875
Epoch 3/400
3/3 [==============================] - 0s 5ms/step - loss: 1.8592 - accuracy: 0.3875
Epoch 4/400
3/3 [==============================] - 0s 7ms/step - loss: 1.8407 - accuracy: 0.3875
Epoch 5/400
3/3 [==============================] - 0s 5ms/step - loss: 1.8237 - accuracy: 0.3875
Epoch 6/400
3/3 [==============================] - 0s 5ms/step - loss: 1.8075 - accuracy: 0.4625
Epoch 7/400
3/3 [==============================] - 0s 6ms/step - loss: 1.7916 - accuracy: 0.4875
Epoch 8/400
3/3 [==============================] - 0s 6ms/step - loss: 1.7766 - accuracy: 0.4875
Epoch 9/400
3/3 [==============================] - 0s 4ms/step - loss: 1.7593 - accuracy: 0.5000
Epoch 10/400
3/3 [==============================] - 0s 5ms/step - loss: 1.7447 - accuracy: 0.5000
Epoch 11/400
3/3 [===========

3/3 [==============================] - 0s 6ms/step - loss: 1.0696 - accuracy: 0.5875
Epoch 85/400
3/3 [==============================] - 0s 7ms/step - loss: 1.0634 - accuracy: 0.5875
Epoch 86/400
3/3 [==============================] - 0s 3ms/step - loss: 1.0571 - accuracy: 0.5875
Epoch 87/400
3/3 [==============================] - 0s 4ms/step - loss: 1.0510 - accuracy: 0.5875
Epoch 88/400
3/3 [==============================] - 0s 4ms/step - loss: 1.0448 - accuracy: 0.5875
Epoch 89/400
3/3 [==============================] - 0s 4ms/step - loss: 1.0388 - accuracy: 0.5875
Epoch 90/400
3/3 [==============================] - 0s 5ms/step - loss: 1.0328 - accuracy: 0.5750
Epoch 91/400
3/3 [==============================] - 0s 4ms/step - loss: 1.0269 - accuracy: 0.5750
Epoch 92/400
3/3 [==============================] - 0s 4ms/step - loss: 1.0208 - accuracy: 0.5750
Epoch 93/400
3/3 [==============================] - 0s 3ms/step - loss: 1.0153 - accuracy: 0.5750
Epoch 94/400
3/3 [===============

3/3 [==============================] - 0s 4ms/step - loss: 0.6857 - accuracy: 0.8250
Epoch 168/400
3/3 [==============================] - 0s 5ms/step - loss: 0.6829 - accuracy: 0.8250
Epoch 169/400
3/3 [==============================] - 0s 4ms/step - loss: 0.6801 - accuracy: 0.8250
Epoch 170/400
3/3 [==============================] - 0s 5ms/step - loss: 0.6772 - accuracy: 0.8250
Epoch 171/400
3/3 [==============================] - 0s 5ms/step - loss: 0.6746 - accuracy: 0.8250
Epoch 172/400
3/3 [==============================] - 0s 5ms/step - loss: 0.6717 - accuracy: 0.8250
Epoch 173/400
3/3 [==============================] - 0s 4ms/step - loss: 0.6691 - accuracy: 0.8250
Epoch 174/400
3/3 [==============================] - 0s 3ms/step - loss: 0.6665 - accuracy: 0.8250
Epoch 175/400
3/3 [==============================] - 0s 6ms/step - loss: 0.6636 - accuracy: 0.8375
Epoch 176/400
3/3 [==============================] - 0s 4ms/step - loss: 0.6610 - accuracy: 0.8375
Epoch 177/400
3/3 [=====

3/3 [==============================] - 0s 5ms/step - loss: 0.5152 - accuracy: 0.8625
Epoch 250/400
3/3 [==============================] - 0s 5ms/step - loss: 0.5138 - accuracy: 0.8625
Epoch 251/400
3/3 [==============================] - 0s 7ms/step - loss: 0.5124 - accuracy: 0.8625
Epoch 252/400
3/3 [==============================] - 0s 6ms/step - loss: 0.5110 - accuracy: 0.8625
Epoch 253/400
3/3 [==============================] - 0s 5ms/step - loss: 0.5095 - accuracy: 0.8625
Epoch 254/400
3/3 [==============================] - 0s 10ms/step - loss: 0.5081 - accuracy: 0.8625
Epoch 255/400
3/3 [==============================] - 0s 5ms/step - loss: 0.5067 - accuracy: 0.8625
Epoch 256/400
3/3 [==============================] - 0s 8ms/step - loss: 0.5054 - accuracy: 0.8625
Epoch 257/400
3/3 [==============================] - 0s 5ms/step - loss: 0.5041 - accuracy: 0.8625
Epoch 258/400
3/3 [==============================] - 0s 5ms/step - loss: 0.5026 - accuracy: 0.8625
Epoch 259/400
3/3 [====

3/3 [==============================] - 0s 7ms/step - loss: 0.4209 - accuracy: 0.8875
Epoch 332/400
3/3 [==============================] - 0s 9ms/step - loss: 0.4199 - accuracy: 0.8875
Epoch 333/400
3/3 [==============================] - 0s 3ms/step - loss: 0.4190 - accuracy: 0.8875
Epoch 334/400
3/3 [==============================] - 0s 3ms/step - loss: 0.4179 - accuracy: 0.8875
Epoch 335/400
3/3 [==============================] - 0s 3ms/step - loss: 0.4170 - accuracy: 0.8875
Epoch 336/400
3/3 [==============================] - 0s 8ms/step - loss: 0.4160 - accuracy: 0.8875
Epoch 337/400
3/3 [==============================] - 0s 4ms/step - loss: 0.4150 - accuracy: 0.8875
Epoch 338/400
3/3 [==============================] - 0s 7ms/step - loss: 0.4140 - accuracy: 0.8875
Epoch 339/400
3/3 [==============================] - 0s 4ms/step - loss: 0.4131 - accuracy: 0.8875
Epoch 340/400
3/3 [==============================] - 0s 6ms/step - loss: 0.4121 - accuracy: 0.8875
Epoch 341/400
3/3 [=====

In [35]:
print ('Test accuracy=',round(acct*100,2))

Test accuracy= 95.24


In [38]:
import numpy
row=[1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1]
yhat=model.predict([row])
print('Predicted: %s (class=%d)' % (yhat, numpy.argmax(yhat)))



Predicted: [[4.0999604e-03 9.9057204e-01 1.4876963e-03 1.2388556e-05 9.8591290e-06
  3.5623775e-03 2.3346108e-04 2.2241358e-05]] (class=1)
